name: Binary Search Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++ and dependencies
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y g++
          sudo apt-get install -y libidn2-0
          wget http://archive.ubuntu.com/ubuntu/pool/main/libi/libidn11/libidn11_1.33-2ubuntu1_amd64.deb || echo "libidn11 not found"
          sudo apt-get install -y libidn2-0
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          choco install mingw
        fi

    - name: Set up CMake
      uses: lukka/get-cmake@v3.27.1

    - name: Configure and Build with g++
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=g++
        cmake --build .

    - name: Run Unit Tests
      run: |
        cd build
        ctest --output-on-failure
